name: Terraform Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.6

      - name: Terraform Format Check
        run: terraform fmt -check

  terraform-plan:
    runs-on: ubuntu-latest
    needs: terraform-check

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.6

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        audience: sts.amazonaws.com
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubActionsRole
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Terraform Init
      run: |
        terraform init \
          -backend-config="bucket=${{ secrets.TFSTATE_S3_BUCKET }}" \
          -backend-config="region=${{ secrets.AWS_REGION }}" \
          -backend-config="key=state/terraform.tfstate" \
          -backend-config="encrypt=true"

    - name: Terraform Plan
      run: terraform plan
      env:
        TF_VAR_s3_bucket_name: ${{ secrets.TF_S3_BUCKET_NAME }}
        TF_VAR_region: ${{ secrets.AWS_REGION }}
        TF_VAR_environment: ${{ vars.TF_ENVIRONMENT }}

  terraform-plan:
    runs-on: ubuntu-latest
    needs: terraform-plan

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.6

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        audience: sts.amazonaws.com
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubActionsRole
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Terraform Init
      run: |
        terraform init \
          -backend-config="bucket=${{ secrets.TFSTATE_S3_BUCKET }}" \
          -backend-config="region=${{ secrets.AWS_REGION }}" \
          -backend-config="key=state/terraform.tfstate" \
          -backend-config="encrypt=true"

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        TF_VAR_s3_bucket_name: ${{ secrets.TF_S3_BUCKET_NAME }}
        TF_VAR_region: ${{ secrets.AWS_REGION }}
        TF_VAR_environment: ${{ vars.TF_ENVIRONMENT }}